### PR TITLE
AVS-421_79 - Don't re-case keys since the server takes care of that

### PR DESCRIPTION
**Pull request by sjb9774**

### CODE REVIEW

**Comment by rsisco** [comment]
@sjb9774 - Did you confirm that removing this code doesn't affect backwards-compatibility with Magento 2.1?

**Comment by sjb9774** [comment]
> @sjb9774 - Did you confirm that removing this code doesn't affect backwards-compatibility with Magento 2.1?

I've just tested happy path checkout locally on 2.1.15 with this change and there were no issues.

**Comment by rsisco** [comment]
Just as an extra note, it appears the code being removed was previously necessary, but no longer is and now causes an issue.

**Comment by rsisco** [comment]
This addresses issue #115.

**Pull request merged**
