### PR TITLE
Revert "Fixes setup:di:compile issues"

### PR DESCRIPTION
**Pull request by erikhansen**
Reverts classyllama/ClassyLlama_AvaTax#12

See comment here for explanation: https://github.com/classyllama/ClassyLlama_AvaTax/pull/12#issuecomment-219154868

### CODE REVIEW

**Comment by erikhansen** [comment]
@jksimoniii Can you provide steps to reproduce the issue, as I've not been able to reproduce the issue? I assume you've installed the module using Composer and are running `bin/magento setup:di:compile` or `bin/magento setup:di:compile-multi-tenant`?

**Comment by jksimoniii** [comment]
I am using PHP v5.6.21.

Steps to reproduce:
```
rm -rf vendor/classyllama var/cache var/page_cage var/generation var/di
composer install
./bin/magento setup:di:compile
```
The result is as follows
```
 [ErrorException]                                       
  ltrim() expects parameter 1 to be string, array given 
```

**Comment by erikhansen** [comment]
@jksimoniii Are you able to compile if you use `bin/magento setup:di:compile-multi-tenant`? Magento's documentation says that `setup:di:compile` is not fully supported: http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-compiler.html#config-cli-subcommands-single

Also, @SamTay submitted a pull request to core Magento to fix the ltrim issue, per my comment here: https://github.com/classyllama/ClassyLlama_AvaTax/issues/13#issuecomment-219155895

**Comment by erikhansen** [comment]
@jksimoniii Per the suggestion from @mttjohnson [here](https://github.com/magento/magento2/pull/4081#issuecomment-219749439) I'm going to test changing the "0" and "1" keys to "1" and "2" to see if it fixes the problem. Standby.

**Comment by jksimoniii** [comment]
Changing to "1" and "2" seemed to work for me.

@erikhansen

**Comment by erikhansen** [comment]
@jksimoniii Yeah, it worked for me too. I've deployed the fix in a new 0.2.2 release: https://github.com/classyllama/ClassyLlama_AvaTax/releases Thanks for your feedback.

**Pull request merged**
