### PR TITLE
Fixes setup:di:compile issues

### PR DESCRIPTION
**Pull request by SamTay**
See magento/magento2#4081

### CODE REVIEW

**Comment by erikhansen** [comment]
@SamTay Thanks for submitting this pull request. I merged the PR in order to test it, but after testing I found that the PR broke the "file" logging handler. You can see details about why on this Magento issue: https://github.com/magento/magento2/issues/2529#issuecomment-219154543 

I'll be reverting this pull request merge.

**Comment by mttjohnson** [comment]
@erikhansen Would it be possible to test array item names starting with "1" instead of "0". I think some of the problems may be related to the interpretation of the string "0" being evaluated as false.

    <type name="ClassyLlama\AvaTax\Model\Logger\AvaTaxLogger">
        <arguments>
            <argument name="name" xsi:type="string">avatax</argument>
            <argument name="handlers"  xsi:type="array">
                <item name="1" xsi:type="object">ClassyLlama\AvaTax\Model\Logger\DbHandler</item>
                <item name="2" xsi:type="object">ClassyLlama\AvaTax\Model\Logger\FileHandler</item>
            </argument>
            <argument name="processors"  xsi:type="array">
                <item name="1" xsi:type="object">ClassyLlama\AvaTax\Model\Logger\AvaTaxProcessor</item>
            </argument>
        </arguments>
    </type>
    <type name="Monolog\Processor\IntrospectionProcessor">
        <arguments>
            <argument name="skipClassesPartials"  xsi:type="array">
                <item name="1" xsi:type="string">ClassyLlama\AvaTax\Model\Logger\DbHandler</item>
                <item name="2" xsi:type="string">ClassyLlama\AvaTax\Model\Logger\FileHandler</item>
            </argument>
        </arguments>
    </type>

**Comment by erikhansen** [comment]
@mttjohnson Thanks for your suggestion! Changing that fixed the problem, so I've pushed the fix out in a new release: https://github.com/classyllama/ClassyLlama_AvaTax/releases

**Comment by davidalger** [comment]
Oh the joys of auto type-casting… ;)

**Comment by SamTay** [comment]
Oops, sorry about that.

**Pull request merged**
